
name: Create Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.event.repository.name }}-${{ github.ref_name }}" \
            --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
